#!/usr/bin/env python3
"""Seed generator — the seven shipped CSVs → one idempotent SQL migration.

    python3 Tools/content/seed_from_csv.py            # writes the SQL, prints a summary
    python3 Tools/content/seed_from_csv.py --stdout   # SQL to stdout instead
    python3 Tools/content/seed_from_csv.py --apply    # ALSO apply it over PostgREST
    python3 Tools/content/seed_from_csv.py --catalogs level_up_costs --out <path>

Output: ../playlife/backend/migrations/2026_08_24_content_seed.sql
(override with --out; the path is resolved relative to the CWD).

`--catalogs` seeds a SUBSET, which is what a catalog added after day one needs:
the day-one migration is the applied record of that day and is not re-generated,
so a new catalog arrives as its own scoped seed file next to it (the exporter and
importer already took the same flag). Everything else about the output is
identical — same statements, same conflict handling — so a subset seed is not a
different kind of file, only a shorter one.

Spec: Docs/Specs/Active/content_catalog/SPEC.md §A2.
Plan: Docs/CONTENT_PIPELINE_PLAN.md §3 ("day-one parity is exact by construction").

What it emits, per SPEC §A2:

  * `INSERT ... ON CONFLICT DO NOTHING` into BOTH `content_rows` and
    `content_drafts` — drafts are the working set an admin edits, and a publish
    upserts drafts into rows, so seeding rows alone would make the very first
    publish look like it deleted nothing and changed everything.
  * every row stamped `version = 1`, `min_build = 0`, `is_active = true`.
  * `update content_catalogs set published_version = 1`.
  * ONE ADDITION beyond the spec text: a `content_versions` row per catalog
    holding the v1 snapshot. Without it v1 is the one version nobody can roll
    back TO — `content_rollback` reads `content_versions`, and the seed is the
    only version that is never produced by `content_publish`. Flagged in
    IMPLEMENTER_REPORT.md as a deliberate addition.

`data` values are STRINGS, VERBATIM. No int/bool coercion: the Unity parsers
already parse strings, and coercing here is how `"7"` and `7` start disagreeing
across the CSV/JSON boundary (SPEC §A2).

`--apply` performs exactly the same inserts over PostgREST with the service key,
so Stage A can be run end-to-end without a human pasting 1.3 MB into the
Supabase SQL editor. It is the same statements, same conflict handling
(`Prefer: resolution=ignore-duplicates` == `on conflict do nothing`); the .sql
file remains the archive of record. DDL still goes through the SQL editor —
this touches data only.

Deterministic: rows are emitted sorted by `row_id`, so re-running after a CSV
edit produces a reviewable diff rather than a reshuffle. (Row ORDER in the repo
CSV is not carried here — the exporter takes order from the existing file. See
catalogs.py.)

Escaping: ordinary single-quoted SQL literals with `''` doubling. Postgres runs
with `standard_conforming_strings = on`, so the literal backslashes that live in
LocalizationText.csv (`HOME_MAINTENANCE_BODY` contains a two-character `\\n`) stay
two characters. Do NOT switch these to E'' strings.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from catalogs import CATALOGS, CATALOGS_BY_NAME, REPO_ROOT, read_csv  # noqa: E402

DEFAULT_OUT = os.path.join(
    os.path.dirname(REPO_ROOT), "playlife", "backend", "migrations", "2026_08_24_content_seed.sql"
)

SEED_VERSION = 1
BATCH = 100  # rows per INSERT statement — keeps single statements pasteable


def sql_str(value: str) -> str:
    """A Postgres text literal. `''` doubling only; see the module docstring."""
    return "'" + value.replace("'", "''") + "'"


def sql_json(obj) -> str:
    return sql_str(json.dumps(obj, ensure_ascii=False, sort_keys=False))


def emit(out, line: str = "") -> None:
    out.write(line + "\n")


def generate(out, repo_root: str = REPO_ROOT, catalogs=None, filename=None) -> dict:
    """Emit the seed SQL for `catalogs` (default: every catalog in the table)."""
    cats = tuple(catalogs) if catalogs is not None else CATALOGS
    counts = {}
    scoped = len(cats) != len(CATALOGS)
    name = filename or ("2026_08_24_content_seed.sql" if not scoped
                        else "content_seed_" + "_".join(c.name for c in cats) + ".sql")

    emit(out, "-- " + "=" * 74)
    emit(out, f"-- {name}")
    emit(out, "-- GENERATED by Tools/content/seed_from_csv.py (GolfinRedux). DO NOT HAND-EDIT:")
    emit(out, "-- re-run the generator instead, so the CSVs stay the single source.")
    emit(out, "--")
    emit(out, f"-- Seeds content_rows + content_drafts from {len(cats)} repo CSV(s) "
              "at version 1,")
    emit(out, "-- and snapshots v1 into content_versions.")
    emit(out, "--")
    emit(out, "-- Spec:  GolfinRedux/Docs/Specs/Active/content_catalog/SPEC.md §A2")
    emit(out, "-- Needs: 2026_08_24_content_catalog.sql (the tables)")
    emit(out, "-- Idempotent: ON CONFLICT DO NOTHING everywhere; safe to re-run.")
    emit(out, "-- " + "=" * 74)
    emit(out)
    emit(out, "begin;")
    emit(out)

    # The registry row every content_rows FK points at. Emitted for EVERY catalog,
    # not only new ones: it is a no-op for the seven the day-one migration already
    # inserted, and it is what makes a scoped seed for a NEW catalog self-
    # sufficient rather than silently failing its foreign key.
    emit(out, "-- " + "-" * 72)
    emit(out, "-- Registry rows (no-op for catalogs 2026_08_24_content_catalog.sql created).")
    emit(out, "-- " + "-" * 72)
    emit(out, "insert into content_catalogs (name) values")
    for i, cat in enumerate(cats):
        emit(out, f"  ({sql_str(cat.name)}){',' if i < len(cats) - 1 else ''}")
    emit(out, "on conflict (name) do nothing;")
    emit(out)

    for cat in cats:
        f = read_csv(cat, repo_root)
        rows = sorted(f.as_dicts(), key=lambda kv: kv[0])
        counts[cat.name] = len(rows)

        emit(out, "-- " + "-" * 72)
        emit(out, f"-- {cat.name}: {len(rows)} rows from {cat.csv_path}")
        emit(out, "-- " + "-" * 72)
        emit(out)

        for table, extra_cols, extra_vals in (
            ("content_rows", "version, ", f"{SEED_VERSION}, "),
            ("content_drafts", "", ""),
        ):
            for start in range(0, len(rows), BATCH):
                chunk = rows[start : start + BATCH]
                emit(
                    out,
                    f"insert into {table} (catalog, row_id, data, min_build, is_active, {extra_cols}updated_at)",
                )
                emit(out, "values")
                for i, (row_id, data) in enumerate(chunk):
                    tail = "," if i < len(chunk) - 1 else ""
                    emit(
                        out,
                        f"  ({sql_str(cat.name)}, {sql_str(row_id)}, {sql_json(data)}::jsonb, "
                        f"0, true, {extra_vals}now()){tail}",
                    )
                emit(out, "on conflict (catalog, row_id) do nothing;")
                emit(out)

        # v1 snapshot — see the module docstring. Built from content_rows so it is
        # whatever actually landed, not what this file hoped would land.
        emit(out, f"insert into content_versions (catalog, version, snapshot, published_by, note)")
        emit(out, "select")
        emit(out, f"  {sql_str(cat.name)},")
        emit(out, f"  {SEED_VERSION},")
        emit(out, "  coalesce(jsonb_agg(jsonb_build_object(")
        emit(out, "    'row_id', r.row_id, 'data', r.data,")
        emit(out, "    'min_build', r.min_build, 'is_active', r.is_active")
        emit(out, "  ) order by r.row_id), '[]'::jsonb),")
        emit(out, "  'seed_from_csv.py',")
        emit(out, f"  'seed from repo CSVs ({cat.csv_path})'")
        emit(out, "from content_rows r")
        emit(out, f"where r.catalog = {sql_str(cat.name)}")
        emit(out, "on conflict (catalog, version) do nothing;")
        emit(out)

    names = ", ".join(sql_str(c.name) for c in cats)
    emit(out, "-- " + "-" * 72)
    emit(out, "-- Publish the seed: every catalog goes to v1.")
    emit(out, "-- " + "-" * 72)
    emit(out, "update content_catalogs")
    emit(out, f"   set published_version = {SEED_VERSION}, updated_at = now()")
    emit(out, f" where name in ({names})")
    emit(out, f"   and published_version < {SEED_VERSION};")
    emit(out)
    emit(out, "commit;")
    emit(out)

    emit(out, "-- " + "-" * 72)
    emit(out, "-- VERIFICATION — run after applying, paste the output.")
    emit(out, "-- Expected: " + ", ".join(f"{k} {v}" for k, v in counts.items()))
    emit(out, "-- " + "-" * 72)
    emit(out, "select catalog, count(*) as rows, min(version) as min_v, max(version) as max_v")
    emit(out, "  from content_rows group by catalog")
    emit(out, "union all")
    emit(out, "select 'DRAFTS:' || catalog, count(*), null, null")
    emit(out, "  from content_drafts group by catalog")
    emit(out, " order by 1;")
    emit(out)
    emit(out, "select name, published_version, is_enabled from content_catalogs order by name;")

    return counts


# ---------------------------------------------------------------------------
# --apply: the same inserts, over PostgREST
# ---------------------------------------------------------------------------


def apply_over_rest(repo_root: str = REPO_ROOT, env_file=None, batch: int = 200,
                    catalogs=None) -> None:
    """Insert the seed directly, service-key over PostgREST. Data only, no DDL."""
    from rest import PostgrestClient  # local import: only --apply needs credentials

    cats = tuple(catalogs) if catalogs is not None else CATALOGS
    client = PostgrestClient.from_env(env_file)
    client.insert_ignore_duplicates("content_catalogs", [{"name": c.name} for c in cats])
    for cat in cats:
        f = read_csv(cat, repo_root)
        rows = sorted(f.as_dicts(), key=lambda kv: kv[0])

        payload_rows = [
            {
                "catalog": cat.name,
                "row_id": rid,
                "data": data,
                "min_build": 0,
                "is_active": True,
                "version": SEED_VERSION,
            }
            for rid, data in rows
        ]
        payload_drafts = [{k: v for k, v in r.items() if k != "version"} for r in payload_rows]

        for table, payload in (("content_rows", payload_rows), ("content_drafts", payload_drafts)):
            for start in range(0, len(payload), batch):
                client.insert_ignore_duplicates(table, payload[start : start + batch])

        # v1 snapshot, built from what is now published (mirrors the SQL's SELECT).
        published = client.select(
            "content_rows",
            {"catalog": f"eq.{cat.name}", "select": "row_id,data,min_build,is_active", "order": "row_id"},
        )
        client.insert_ignore_duplicates(
            "content_versions",
            [
                {
                    "catalog": cat.name,
                    "version": SEED_VERSION,
                    "snapshot": published,
                    "published_by": "seed_from_csv.py",
                    "note": f"seed from repo CSVs ({cat.csv_path})",
                }
            ],
        )
        print(f"  applied {cat.name:<13} {len(payload_rows):>4} rows (published now {len(published)})")

    client.patch(
        "content_catalogs",
        {"name": "in.(" + ",".join(c.name for c in cats) + ")", "published_version": f"lt.{SEED_VERSION}"},
        {"published_version": SEED_VERSION},
    )
    print("  content_catalogs.published_version -> 1")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=DEFAULT_OUT, help=f"output .sql path (default: {DEFAULT_OUT})")
    ap.add_argument("--stdout", action="store_true", help="write SQL to stdout instead of --out")
    ap.add_argument("--apply", action="store_true", help="also apply the seed over PostgREST")
    ap.add_argument("--repo-root", default=REPO_ROOT)
    ap.add_argument("--env-file", default=None, help="dotenv file with SUPABASE_* (for --apply)")
    ap.add_argument("--catalogs", default=None,
                    help="comma-separated subset (default: every catalog in catalogs.py)")
    args = ap.parse_args()

    cats = None
    if args.catalogs:
        names = [n.strip() for n in args.catalogs.split(",") if n.strip()]
        unknown = [n for n in names if n not in CATALOGS_BY_NAME]
        if unknown:
            raise SystemExit(
                f"unknown catalog(s): {unknown}. Known: {[c.name for c in CATALOGS]}")
        cats = tuple(CATALOGS_BY_NAME[n] for n in names)

        # A scoped seed must never land on DEFAULT_OUT. The day-one migration is
        # the applied record of that day (see the module docstring); writing a
        # subset there replaces seven catalogs with however few `--catalogs`
        # named, and the loss is silent — the run reports success either way.
        # `generate()` already draws this line for the FILENAME it stamps in the
        # header (`scoped` -> content_seed_<names>.sql); this is the same line,
        # drawn for the path actually written. `--stdout` writes no file and so
        # is deliberately not guarded.
        if not args.stdout and os.path.abspath(args.out) == os.path.abspath(DEFAULT_OUT):
            raise SystemExit(
                f"refusing to write a scoped seed ({', '.join(names)}) over "
                f"{DEFAULT_OUT}\n"
                "  That file is the day-one migration — the applied record of that "
                "day — and is not re-generated.\n"
                "  A catalog added after day one arrives as its OWN seed file: "
                "pass --out <new migration path>\n"
                "  (e.g. --out " + os.path.join(os.path.dirname(DEFAULT_OUT),
                                                "content_seed_" + "_".join(names) + ".sql") + ")"
            )

    if args.stdout:
        counts = generate(sys.stdout, args.repo_root, cats)
        return 0

    out_path = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    import io as _io

    buf = _io.StringIO()
    counts = generate(buf, args.repo_root, cats, os.path.basename(out_path))
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(buf.getvalue())

    total = sum(counts.values())
    print(f"wrote {out_path}")
    print(f"  {len(buf.getvalue()):,} bytes, {total} rows across {len(counts)} catalogs")
    for name, n in counts.items():
        print(f"    {name:<13} {n:>4}")

    if args.apply:
        print("applying over PostgREST...")
        apply_over_rest(args.repo_root, args.env_file, catalogs=cats)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
