// ─────────────────────────────────────────────────────────────────────────────
// Golfin.Tournaments — BotFieldConfig / BotCard
// tournament_bot_fields.csv (GDD §7). Rolling logic is T3; T1 defines shape only.
// ─────────────────────────────────────────────────────────────────────────────
#nullable enable
using System;
using System.Collections.Generic;

namespace Golfin.Tournaments
{
    /// <summary>
    /// Configuration for a bot field (one row of tournament_bot_fields.csv, GDD §7).
    /// The actual bot pre-roll (T3) reads these params to generate
    /// <see cref="BotCard"/> instances deterministically from (seed, now).
    /// </summary>
    public sealed class BotFieldConfig
    {
        /// <summary>Stable id matching the <c>botFieldId</c> column in tournaments.csv.</summary>
        public string BotFieldId { get; }

        /// <summary>Total number of bot entries in the field.</summary>
        public int BotCount { get; }

        /// <summary>
        /// Skill-bracket weight distribution (maps difficulty tier → fraction of bots).
        /// Keys come from <c>Assets/Resources/Data/bot_difficulty.csv</c> bracket ids.
        /// SPEC §4 hard-reuse mandate: these ids must match bot_difficulty.csv exactly.
        /// </summary>
        public IReadOnlyDictionary<string, float> BracketWeights { get; }

        /// <summary>
        /// Minimum start-offset from <c>startUtc</c> in seconds.
        /// Each bot's start time is (startUtc + random-seeded value in [StartOffsetMinSec, StartOffsetMaxSec]).
        /// </summary>
        public float StartOffsetMinSec { get; }

        /// <summary>
        /// Maximum start-offset from <c>startUtc</c> in seconds.
        /// Drives the organic reveal spread (GDD §7 "pace schedule").
        /// </summary>
        public float StartOffsetMaxSec { get; }

        /// <summary>
        /// Per-hole time spread in seconds.
        /// Each bot's per-hole completion time is jittered by this amount around
        /// the bracket-average pace (seeded deterministically).
        /// </summary>
        public float PerHoleSpreadSec { get; }

        public BotFieldConfig(
            string botFieldId,
            int botCount,
            IReadOnlyDictionary<string, float> bracketWeights,
            float startOffsetMinSec,
            float startOffsetMaxSec,
            float perHoleSpreadSec)
        {
            BotFieldId        = botFieldId;
            BotCount          = botCount;
            BracketWeights    = bracketWeights;
            StartOffsetMinSec = startOffsetMinSec;
            StartOffsetMaxSec = startOffsetMaxSec;
            PerHoleSpreadSec  = perHoleSpreadSec;
        }
    }

    /// <summary>
    /// Pre-rolled result card for one bot in a tournament field (GDD §7).
    /// Shape defined in T1; the full card is generated by T3 (tournament_bot_field).
    /// <para>
    /// Identity: <see cref="BotId"/> references a row in
    /// <c>Assets/Resources/Data/fake_players.csv</c> — the same 100+ roster used
    /// by Rankings and 1v1 (SPEC §4 hard-reuse mandate).
    /// </para>
    /// <para>
    /// Organic reveal: <see cref="PerHoleCompletionUtc"/> contains the seeded
    /// per-hole completion timestamps. <see cref="ITournamentBackend.GetLeaderboard"/>
    /// projects each bot through its schedule at <c>UtcNow</c>, so scores trickle
    /// onto the board over the window (GDD §7).
    /// </para>
    /// </summary>
    public sealed class BotCard
    {
        /// <summary>
        /// Bot identity id — must match a row id in
        /// <c>Assets/Resources/Data/fake_players.csv</c>.
        /// Do not define new players here; reuse the existing roster.
        /// </summary>
        public string BotId { get; }

        /// <summary>Strokes for each hole (parallel to TournamentDefinition.HoleSet).</summary>
        public IReadOnlyList<int> PerHoleStrokes { get; }

        /// <summary>Sum of PerHoleStrokes (convenience; sort key on the board).</summary>
        public int TotalStrokes { get; }

        /// <summary>Seeded start offset in seconds from startUtc for organic reveal pacing.</summary>
        public float StartOffsetSeconds { get; }

        /// <summary>
        /// Seeded per-hole completion UTC timestamps.
        /// <c>GetLeaderboard(now)</c> only exposes holes whose completion time is &lt;= now,
        /// simulating natural game-world play progression (GDD §7 organic reveal).
        /// </summary>
        public IReadOnlyList<DateTime> PerHoleCompletionUtc { get; }

        public BotCard(
            string botId,
            IReadOnlyList<int> perHoleStrokes,
            int totalStrokes,
            float startOffsetSeconds,
            IReadOnlyList<DateTime> perHoleCompletionUtc)
        {
            BotId                = botId;
            PerHoleStrokes       = perHoleStrokes;
            TotalStrokes         = totalStrokes;
            StartOffsetSeconds   = startOffsetSeconds;
            PerHoleCompletionUtc = perHoleCompletionUtc;
        }
    }
}
