@echo off
echo Exporting  UHole GEO...
cd /d "%~dp0"
node scripts/generate-terrain.mjs lomond-country-club 1
node scripts/export-hole.mjs lomond-country-club 1
node scripts/generate-terrain.mjs lomond-country-club 2
node scripts/export-hole.mjs lomond-country-club 2
node scripts/generate-terrain.mjs lomond-country-club 3
node scripts/export-hole.mjs lomond-country-club 3
node scripts/generate-terrain.mjs lomond-country-club 4
node scripts/export-hole.mjs lomond-country-club 4
node scripts/generate-terrain.mjs lomond-country-club 5
node scripts/export-hole.mjs lomond-country-club 5
node scripts/generate-terrain.mjs lomond-country-club 6
node scripts/export-hole.mjs lomond-country-club 6
node scripts/generate-terrain.mjs lomond-country-club 7
node scripts/export-hole.mjs lomond-country-club 7
node scripts/generate-terrain.mjs lomond-country-club 8
node scripts/export-hole.mjs lomond-country-club 8
node scripts/generate-terrain.mjs lomond-country-club 9
node scripts/export-hole.mjs lomond-country-club 9
node scripts/generate-terrain.mjs lomond-country-club 10
node scripts/export-hole.mjs lomond-country-club 10
node scripts/generate-terrain.mjs lomond-country-club 11
node scripts/export-hole.mjs lomond-country-club 11
node scripts/generate-terrain.mjs lomond-country-club 12
node scripts/export-hole.mjs lomond-country-club 12
node scripts/generate-terrain.mjs lomond-country-club 13
node scripts/export-hole.mjs lomond-country-club 13
node scripts/generate-terrain.mjs lomond-country-club 14
node scripts/export-hole.mjs lomond-country-club 14
node scripts/generate-terrain.mjs lomond-country-club 15
node scripts/export-hole.mjs lomond-country-club 15
node scripts/generate-terrain.mjs lomond-country-club 16
node scripts/export-hole.mjs lomond-country-club 16
node scripts/generate-terrain.mjs lomond-country-club 17
node scripts/export-hole.mjs lomond-country-club 17
node scripts/generate-terrain.mjs lomond-country-club 18
node scripts/export-hole.mjs lomond-country-club 18
pause
