// AUTO-GENERATED by golfin-implementer — iteration 3 — delete after screenshot captured
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using System.IO;

[InitializeOnLoad]
public static class AutoScreenshotHUD
{
    private const string ScenePath = "Assets/Scenes/Physics/LabScaffold.unity";
    private const string ScreenshotDir = "Assets/Screenshots";
    private const string SentinelKey = "AutoScreenshotHUD_Triggered_Iter3v3";

    static AutoScreenshotHUD()
    {
        if (SessionState.GetBool(SentinelKey, false)) return;

        // If already in play mode when compiled, wait for exit
        if (EditorApplication.isPlaying || EditorApplication.isPlayingOrWillChangePlaymode)
        {
            EditorApplication.playModeStateChanged += OnPlayModeExited;
            return;
        }

        // In edit mode — enter play mode now
        EditorApplication.playModeStateChanged += OnPlayModeChanged;
        EditorApplication.delayCall += StartPlayMode;
    }

    static void OnPlayModeExited(PlayModeStateChange state)
    {
        if (state == PlayModeStateChange.EnteredEditMode)
        {
            EditorApplication.playModeStateChanged -= OnPlayModeExited;
            EditorApplication.playModeStateChanged += OnPlayModeChanged;
            EditorApplication.delayCall += StartPlayMode;
        }
    }

    static void StartPlayMode()
    {
        if (SessionState.GetBool(SentinelKey, false)) return;
        SessionState.SetBool(SentinelKey, true);

        var currentScene = UnityEngine.SceneManagement.SceneManager.GetActiveScene();
        if (!currentScene.path.Contains("LabScaffold"))
            EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);

        EditorApplication.EnterPlaymode();
    }

    static void OnPlayModeChanged(PlayModeStateChange state)
    {
        if (state == PlayModeStateChange.EnteredPlayMode)
        {
            EditorApplication.delayCall += () =>
            {
                EditorApplication.delayCall += () =>
                {
                    EditorApplication.delayCall += CaptureAndStop;
                };
            };
        }
    }

    static void CaptureAndStop()
    {
        if (!Directory.Exists(ScreenshotDir))
            Directory.CreateDirectory(ScreenshotDir);

        string timestamp = System.DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
        string pngPath = $"{ScreenshotDir}/screenshot_{timestamp}.png";

        ScreenCapture.CaptureScreenshot(pngPath);
        Debug.Log($"[AutoScreenshotHUD] Captured screenshot to {pngPath}");

        EditorApplication.delayCall += () =>
        {
            EditorApplication.delayCall += () =>
            {
                CompressToJpg(pngPath, 800);
                EditorApplication.ExitPlaymode();
                EditorApplication.delayCall += SelfDelete;
            };
        };
    }

    static void SelfDelete()
    {
        const string selfPath = "Assets/Scripts/Editor/AutoScreenshotHUD.cs";
        if (File.Exists(selfPath))
        {
            AssetDatabase.DeleteAsset(selfPath);
            Debug.Log("[AutoScreenshotHUD] Self-deleted after screenshot capture.");
        }
    }

    static void CompressToJpg(string pngPath, int maxWidth)
    {
        if (!File.Exists(pngPath)) return;

        var bytes = File.ReadAllBytes(pngPath);
        var tex = new Texture2D(2, 2);
        tex.LoadImage(bytes);

        int newW = tex.width > maxWidth ? maxWidth : tex.width;
        float ratio = (float)newW / tex.width;
        int newH = Mathf.RoundToInt(tex.height * ratio);

        var rt = RenderTexture.GetTemporary(newW, newH);
        Graphics.Blit(tex, rt);
        var resized = new Texture2D(newW, newH, TextureFormat.RGB24, false);
        RenderTexture.active = rt;
        resized.ReadPixels(new Rect(0, 0, newW, newH), 0, 0);
        resized.Apply();
        RenderTexture.active = null;
        RenderTexture.ReleaseTemporary(rt);

        var jpg = resized.EncodeToJPG(75);
        string jpgPath = pngPath.Replace(".png", ".jpg");
        File.WriteAllBytes(jpgPath, jpg);

        File.Delete(pngPath);
        string metaPath = pngPath + ".meta";
        if (File.Exists(metaPath)) File.Delete(metaPath);

        Object.DestroyImmediate(tex);
        Object.DestroyImmediate(resized);
        Debug.Log($"[AutoScreenshotHUD] Compressed to {jpgPath}");
    }
}
