// AUTO-GENERATED by golfin-implementer — 8_5_d iteration 3 (CESAR_REJECTED #2)
// Uses CaptureHelper.SnapGameView() (synchronous, correct) NOT ScreenCapture.CaptureScreenshot (banned).
// Delete after screenshot captured, or let SelfDelete clean it up.
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using System.IO;
using Golfin.EditorTools;

[InitializeOnLoad]
public static class AutoScreenshotHUD
{
    private const string ScenePath   = "Assets/Scenes/Physics/LabScaffold.unity";
    private const string SentinelKey = "AutoScreenshotHUD_8_5_d_iter3_v2";

    static AutoScreenshotHUD()
    {
        if (SessionState.GetBool(SentinelKey, false)) return;

        // If already in play mode when compiled, wait for exit then re-enter
        if (EditorApplication.isPlaying || EditorApplication.isPlayingOrWillChangePlaymode)
        {
            EditorApplication.playModeStateChanged += OnPlayModeExited;
            return;
        }

        EditorApplication.playModeStateChanged += OnPlayModeChanged;
        EditorApplication.delayCall += StartPlayMode;
    }

    static void OnPlayModeExited(PlayModeStateChange state)
    {
        if (state == PlayModeStateChange.EnteredEditMode)
        {
            EditorApplication.playModeStateChanged -= OnPlayModeExited;
            EditorApplication.playModeStateChanged += OnPlayModeChanged;
            EditorApplication.delayCall += StartPlayMode;
        }
    }

    static void StartPlayMode()
    {
        if (SessionState.GetBool(SentinelKey, false)) return;
        SessionState.SetBool(SentinelKey, true);

        var currentScene = UnityEngine.SceneManagement.SceneManager.GetActiveScene();
        if (!currentScene.path.Contains("LabScaffold"))
            EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);

        EditorApplication.EnterPlaymode();
    }

    // Track frames since entering play mode so we wait long enough
    static int _frameCount = 0;
    const int WAIT_FRAMES = 360; // ~6 seconds at 60fps; plenty for all OnEnable/Start callbacks

    static void OnPlayModeChanged(PlayModeStateChange state)
    {
        if (state == PlayModeStateChange.EnteredPlayMode)
        {
            _frameCount = 0;
            EditorApplication.update += WaitThenCapture;
        }
    }

    static void WaitThenCapture()
    {
        _frameCount++;
        if (_frameCount < WAIT_FRAMES) return;
        EditorApplication.update -= WaitThenCapture;
        CaptureAndStop();
    }

    static void CaptureAndStop()
    {
        // Synchronous capture via CaptureHelper — never ScreenCapture.CaptureScreenshot
        string path = CaptureHelper.SnapGameView();
        Debug.Log($"[AutoScreenshotHUD] Captured to {path}");

        EditorApplication.ExitPlaymode();
        EditorApplication.delayCall += SelfDelete;
    }

    static void SelfDelete()
    {
        const string selfPath = "Assets/Scripts/Editor/AutoScreenshotHUD.cs";
        if (File.Exists(selfPath))
        {
            AssetDatabase.DeleteAsset(selfPath);
            Debug.Log("[AutoScreenshotHUD] Self-deleted after screenshot capture.");
        }
    }
}
