-- ==========================================================================
-- 2026_08_31_content_gacha_seed.sql
-- GENERATED by Tools/content/seed_from_csv.py (GolfinRedux). DO NOT HAND-EDIT:
-- re-run the generator instead, so the CSVs stay the single source.
--
-- Seeds content_rows + content_drafts from 4 repo CSV(s) at version 1,
-- and snapshots v1 into content_versions.
--
-- Spec:  GolfinRedux/Docs/Specs/Active/content_catalog/SPEC.md §A2
-- Needs: 2026_08_24_content_catalog.sql (the tables)
-- Idempotent: ON CONFLICT DO NOTHING everywhere; safe to re-run.
-- ==========================================================================

begin;

-- ------------------------------------------------------------------------
-- Registry rows (no-op for catalogs 2026_08_24_content_catalog.sql created).
-- ------------------------------------------------------------------------
insert into content_catalogs (name) values
  ('gacha_banners'),
  ('gacha_rates'),
  ('gacha_pools'),
  ('ticket_types')
on conflict (name) do nothing;

-- ------------------------------------------------------------------------
-- gacha_banners: 4 rows from Assets/Resources/Data/gacha_banners.csv
-- ------------------------------------------------------------------------

insert into content_rows (catalog, row_id, data, min_build, is_active, version, updated_at)
values
  ('gacha_banners', 'banner_inactive', '{"bannerId": "banner_inactive", "nameKey": "INACTIVE BANNER", "artSprite": "GachaBanner_StandardClub1", "costX1": "50", "costX10": "450", "endUtc": "2027-06-01T00:00:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/inactive", "sortOrder": "10", "active": "false", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "", "pityMinRarity": "", "guaranteeMinRarityX10": "", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "INACTIVE BANNER", "nameJa": "非アクティブバナー", "taglineEn": "", "taglineJa": "", "featuredRefIds": ""}'::jsonb, 0, true, 1, now()),
  ('gacha_banners', 'banner_standard_club1', '{"bannerId": "banner_standard_club1", "nameKey": "STANDARD CLUB 1", "artSprite": "GachaBanner_StandardClub1", "costX1": "50", "costX10": "450", "endUtc": "2027-01-01T00:00:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/standard-club1", "sortOrder": "1", "active": "true", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "50", "pityMinRarity": "Legendary", "guaranteeMinRarityX10": "Rare", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "STANDARD CLUB 1", "nameJa": "スタンダードクラブ 1", "taglineEn": "", "taglineJa": "", "featuredRefIds": "club_pwedge_royal;club_putter_golfinx"}'::jsonb, 0, true, 1, now()),
  ('gacha_banners', 'banner_test_a', '{"bannerId": "banner_test_a", "nameKey": "TEST BANNER A", "artSprite": "GachaBanner_StandardClub1", "costX1": "50", "costX10": "450", "endUtc": "2026-12-31T23:59:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/test-a", "sortOrder": "2", "active": "true", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "", "pityMinRarity": "", "guaranteeMinRarityX10": "", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "TEST BANNER A", "nameJa": "テストバナー A", "taglineEn": "", "taglineJa": "", "featuredRefIds": ""}'::jsonb, 0, true, 1, now()),
  ('gacha_banners', 'banner_test_b', '{"bannerId": "banner_test_b", "nameKey": "TEST BANNER B", "artSprite": "GachaBanner_StandardClub1", "costX1": "75", "costX10": "675", "endUtc": "2026-11-30T00:00:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/test-b", "sortOrder": "3", "active": "true", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "30", "pityMinRarity": "Rare", "guaranteeMinRarityX10": "Uncommon", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "TEST BANNER B", "nameJa": "テストバナー B", "taglineEn": "", "taglineJa": "", "featuredRefIds": "club_awedge_fyloe"}'::jsonb, 0, true, 1, now())
on conflict (catalog, row_id) do nothing;

insert into content_drafts (catalog, row_id, data, min_build, is_active, updated_at)
values
  ('gacha_banners', 'banner_inactive', '{"bannerId": "banner_inactive", "nameKey": "INACTIVE BANNER", "artSprite": "GachaBanner_StandardClub1", "costX1": "50", "costX10": "450", "endUtc": "2027-06-01T00:00:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/inactive", "sortOrder": "10", "active": "false", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "", "pityMinRarity": "", "guaranteeMinRarityX10": "", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "INACTIVE BANNER", "nameJa": "非アクティブバナー", "taglineEn": "", "taglineJa": "", "featuredRefIds": ""}'::jsonb, 0, true, now()),
  ('gacha_banners', 'banner_standard_club1', '{"bannerId": "banner_standard_club1", "nameKey": "STANDARD CLUB 1", "artSprite": "GachaBanner_StandardClub1", "costX1": "50", "costX10": "450", "endUtc": "2027-01-01T00:00:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/standard-club1", "sortOrder": "1", "active": "true", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "50", "pityMinRarity": "Legendary", "guaranteeMinRarityX10": "Rare", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "STANDARD CLUB 1", "nameJa": "スタンダードクラブ 1", "taglineEn": "", "taglineJa": "", "featuredRefIds": "club_pwedge_royal;club_putter_golfinx"}'::jsonb, 0, true, now()),
  ('gacha_banners', 'banner_test_a', '{"bannerId": "banner_test_a", "nameKey": "TEST BANNER A", "artSprite": "GachaBanner_StandardClub1", "costX1": "50", "costX10": "450", "endUtc": "2026-12-31T23:59:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/test-a", "sortOrder": "2", "active": "true", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "", "pityMinRarity": "", "guaranteeMinRarityX10": "", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "TEST BANNER A", "nameJa": "テストバナー A", "taglineEn": "", "taglineJa": "", "featuredRefIds": ""}'::jsonb, 0, true, now()),
  ('gacha_banners', 'banner_test_b', '{"bannerId": "banner_test_b", "nameKey": "TEST BANNER B", "artSprite": "GachaBanner_StandardClub1", "costX1": "75", "costX10": "675", "endUtc": "2026-11-30T00:00:00Z", "rulesUrl": "https://golfin.example.com/gacha-rules/test-b", "sortOrder": "3", "active": "true", "startUtc": "2026-01-01T00:00:00Z", "poolId": "pool_standard_club1", "ticketType": "0", "pityThreshold": "30", "pityMinRarity": "Rare", "guaranteeMinRarityX10": "Uncommon", "maxPullsPerPlayer": "", "artUrl": "", "nameEn": "TEST BANNER B", "nameJa": "テストバナー B", "taglineEn": "", "taglineJa": "", "featuredRefIds": "club_awedge_fyloe"}'::jsonb, 0, true, now())
on conflict (catalog, row_id) do nothing;

insert into content_versions (catalog, version, snapshot, published_by, note)
select
  'gacha_banners',
  1,
  coalesce(jsonb_agg(jsonb_build_object(
    'row_id', r.row_id, 'data', r.data,
    'min_build', r.min_build, 'is_active', r.is_active
  ) order by r.row_id), '[]'::jsonb),
  'seed_from_csv.py',
  'seed from repo CSVs (Assets/Resources/Data/gacha_banners.csv)'
from content_rows r
where r.catalog = 'gacha_banners'
on conflict (catalog, version) do nothing;

-- ------------------------------------------------------------------------
-- gacha_rates: 6 rows from Assets/Resources/Data/gacha_rates.csv
-- ------------------------------------------------------------------------

insert into content_rows (catalog, row_id, data, min_build, is_active, version, updated_at)
values
  ('gacha_rates', 'pool_standard_club1_common', '{"id": "pool_standard_club1_common", "poolId": "pool_standard_club1", "rarity": "Common", "rateBp": "5500"}'::jsonb, 0, true, 1, now()),
  ('gacha_rates', 'pool_standard_club1_legendary', '{"id": "pool_standard_club1_legendary", "poolId": "pool_standard_club1", "rarity": "Legendary", "rateBp": "200"}'::jsonb, 0, true, 1, now()),
  ('gacha_rates', 'pool_standard_club1_mythic', '{"id": "pool_standard_club1_mythic", "poolId": "pool_standard_club1", "rarity": "Mythic", "rateBp": "550"}'::jsonb, 0, true, 1, now()),
  ('gacha_rates', 'pool_standard_club1_rare', '{"id": "pool_standard_club1_rare", "poolId": "pool_standard_club1", "rarity": "Rare", "rateBp": "1200"}'::jsonb, 0, true, 1, now()),
  ('gacha_rates', 'pool_standard_club1_supreme', '{"id": "pool_standard_club1_supreme", "poolId": "pool_standard_club1", "rarity": "Supreme", "rateBp": "50"}'::jsonb, 0, true, 1, now()),
  ('gacha_rates', 'pool_standard_club1_uncommon', '{"id": "pool_standard_club1_uncommon", "poolId": "pool_standard_club1", "rarity": "Uncommon", "rateBp": "2500"}'::jsonb, 0, true, 1, now())
on conflict (catalog, row_id) do nothing;

insert into content_drafts (catalog, row_id, data, min_build, is_active, updated_at)
values
  ('gacha_rates', 'pool_standard_club1_common', '{"id": "pool_standard_club1_common", "poolId": "pool_standard_club1", "rarity": "Common", "rateBp": "5500"}'::jsonb, 0, true, now()),
  ('gacha_rates', 'pool_standard_club1_legendary', '{"id": "pool_standard_club1_legendary", "poolId": "pool_standard_club1", "rarity": "Legendary", "rateBp": "200"}'::jsonb, 0, true, now()),
  ('gacha_rates', 'pool_standard_club1_mythic', '{"id": "pool_standard_club1_mythic", "poolId": "pool_standard_club1", "rarity": "Mythic", "rateBp": "550"}'::jsonb, 0, true, now()),
  ('gacha_rates', 'pool_standard_club1_rare', '{"id": "pool_standard_club1_rare", "poolId": "pool_standard_club1", "rarity": "Rare", "rateBp": "1200"}'::jsonb, 0, true, now()),
  ('gacha_rates', 'pool_standard_club1_supreme', '{"id": "pool_standard_club1_supreme", "poolId": "pool_standard_club1", "rarity": "Supreme", "rateBp": "50"}'::jsonb, 0, true, now()),
  ('gacha_rates', 'pool_standard_club1_uncommon', '{"id": "pool_standard_club1_uncommon", "poolId": "pool_standard_club1", "rarity": "Uncommon", "rateBp": "2500"}'::jsonb, 0, true, now())
on conflict (catalog, row_id) do nothing;

insert into content_versions (catalog, version, snapshot, published_by, note)
select
  'gacha_rates',
  1,
  coalesce(jsonb_agg(jsonb_build_object(
    'row_id', r.row_id, 'data', r.data,
    'min_build', r.min_build, 'is_active', r.is_active
  ) order by r.row_id), '[]'::jsonb),
  'seed_from_csv.py',
  'seed from repo CSVs (Assets/Resources/Data/gacha_rates.csv)'
from content_rows r
where r.catalog = 'gacha_rates'
on conflict (catalog, version) do nothing;

-- ------------------------------------------------------------------------
-- gacha_pools: 11 rows from Assets/Resources/Data/gacha_pools.csv
-- ------------------------------------------------------------------------

insert into content_rows (catalog, row_id, data, min_build, is_active, version, updated_at)
values
  ('gacha_pools', 'psc1_awedge_fyloe', '{"id": "psc1_awedge_fyloe", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_awedge_fyloe", "rarity": "Mythic", "weight": "100", "quantity": "1", "dupeRp": "160", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_ball_golfin', '{"id": "psc1_ball_golfin", "poolId": "pool_standard_club1", "kind": "ball", "refId": "ball_golfin", "rarity": "Common", "weight": "60", "quantity": "3", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_driver_gf', '{"id": "psc1_driver_gf", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_driver_gf", "rarity": "Common", "weight": "100", "quantity": "1", "dupeRp": "20", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_iron7_mireo', '{"id": "psc1_iron7_mireo", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_iron7_mireo", "rarity": "Rare", "weight": "100", "quantity": "1", "dupeRp": "80", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_iron9_klyro', '{"id": "psc1_iron9_klyro", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_iron9_klyro", "rarity": "Uncommon", "weight": "100", "quantity": "1", "dupeRp": "40", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_putter_golfinx', '{"id": "psc1_putter_golfinx", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_putter_golfinx", "rarity": "Supreme", "weight": "100", "quantity": "1", "dupeRp": "600", "featured": "true"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_pwedge_royal', '{"id": "psc1_pwedge_royal", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_pwedge_royal", "rarity": "Legendary", "weight": "100", "quantity": "1", "dupeRp": "300", "featured": "true"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_repairkit_common', '{"id": "psc1_repairkit_common", "poolId": "pool_standard_club1", "kind": "item", "refId": "repairkit_common", "rarity": "Common", "weight": "40", "quantity": "1", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_repairkit_mythic', '{"id": "psc1_repairkit_mythic", "poolId": "pool_standard_club1", "kind": "item", "refId": "repairkit_mythic", "rarity": "Mythic", "weight": "30", "quantity": "1", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_repairkit_rare', '{"id": "psc1_repairkit_rare", "poolId": "pool_standard_club1", "kind": "item", "refId": "repairkit_rare", "rarity": "Rare", "weight": "40", "quantity": "1", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, 1, now()),
  ('gacha_pools', 'psc1_wood_gf', '{"id": "psc1_wood_gf", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_wood_gf", "rarity": "Common", "weight": "100", "quantity": "1", "dupeRp": "20", "featured": "false"}'::jsonb, 0, true, 1, now())
on conflict (catalog, row_id) do nothing;

insert into content_drafts (catalog, row_id, data, min_build, is_active, updated_at)
values
  ('gacha_pools', 'psc1_awedge_fyloe', '{"id": "psc1_awedge_fyloe", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_awedge_fyloe", "rarity": "Mythic", "weight": "100", "quantity": "1", "dupeRp": "160", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_ball_golfin', '{"id": "psc1_ball_golfin", "poolId": "pool_standard_club1", "kind": "ball", "refId": "ball_golfin", "rarity": "Common", "weight": "60", "quantity": "3", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_driver_gf', '{"id": "psc1_driver_gf", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_driver_gf", "rarity": "Common", "weight": "100", "quantity": "1", "dupeRp": "20", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_iron7_mireo', '{"id": "psc1_iron7_mireo", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_iron7_mireo", "rarity": "Rare", "weight": "100", "quantity": "1", "dupeRp": "80", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_iron9_klyro', '{"id": "psc1_iron9_klyro", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_iron9_klyro", "rarity": "Uncommon", "weight": "100", "quantity": "1", "dupeRp": "40", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_putter_golfinx', '{"id": "psc1_putter_golfinx", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_putter_golfinx", "rarity": "Supreme", "weight": "100", "quantity": "1", "dupeRp": "600", "featured": "true"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_pwedge_royal', '{"id": "psc1_pwedge_royal", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_pwedge_royal", "rarity": "Legendary", "weight": "100", "quantity": "1", "dupeRp": "300", "featured": "true"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_repairkit_common', '{"id": "psc1_repairkit_common", "poolId": "pool_standard_club1", "kind": "item", "refId": "repairkit_common", "rarity": "Common", "weight": "40", "quantity": "1", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_repairkit_mythic', '{"id": "psc1_repairkit_mythic", "poolId": "pool_standard_club1", "kind": "item", "refId": "repairkit_mythic", "rarity": "Mythic", "weight": "30", "quantity": "1", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_repairkit_rare', '{"id": "psc1_repairkit_rare", "poolId": "pool_standard_club1", "kind": "item", "refId": "repairkit_rare", "rarity": "Rare", "weight": "40", "quantity": "1", "dupeRp": "0", "featured": "false"}'::jsonb, 0, true, now()),
  ('gacha_pools', 'psc1_wood_gf', '{"id": "psc1_wood_gf", "poolId": "pool_standard_club1", "kind": "club", "refId": "club_wood_gf", "rarity": "Common", "weight": "100", "quantity": "1", "dupeRp": "20", "featured": "false"}'::jsonb, 0, true, now())
on conflict (catalog, row_id) do nothing;

insert into content_versions (catalog, version, snapshot, published_by, note)
select
  'gacha_pools',
  1,
  coalesce(jsonb_agg(jsonb_build_object(
    'row_id', r.row_id, 'data', r.data,
    'min_build', r.min_build, 'is_active', r.is_active
  ) order by r.row_id), '[]'::jsonb),
  'seed_from_csv.py',
  'seed from repo CSVs (Assets/Resources/Data/gacha_pools.csv)'
from content_rows r
where r.catalog = 'gacha_pools'
on conflict (catalog, version) do nothing;

-- ------------------------------------------------------------------------
-- ticket_types: 2 rows from Assets/Resources/Data/ticket_types.csv
-- ------------------------------------------------------------------------

insert into content_rows (catalog, row_id, data, min_build, is_active, version, updated_at)
values
  ('ticket_types', '0', '{"id": "0", "key": "standard", "nameEn": "Ticket", "nameJa": "チケット", "iconSprite": "", "iconUrl": ""}'::jsonb, 0, true, 1, now()),
  ('ticket_types', '1', '{"id": "1", "key": "gold", "nameEn": "Gold Ticket", "nameJa": "ゴールドチケット", "iconSprite": "", "iconUrl": ""}'::jsonb, 0, true, 1, now())
on conflict (catalog, row_id) do nothing;

insert into content_drafts (catalog, row_id, data, min_build, is_active, updated_at)
values
  ('ticket_types', '0', '{"id": "0", "key": "standard", "nameEn": "Ticket", "nameJa": "チケット", "iconSprite": "", "iconUrl": ""}'::jsonb, 0, true, now()),
  ('ticket_types', '1', '{"id": "1", "key": "gold", "nameEn": "Gold Ticket", "nameJa": "ゴールドチケット", "iconSprite": "", "iconUrl": ""}'::jsonb, 0, true, now())
on conflict (catalog, row_id) do nothing;

insert into content_versions (catalog, version, snapshot, published_by, note)
select
  'ticket_types',
  1,
  coalesce(jsonb_agg(jsonb_build_object(
    'row_id', r.row_id, 'data', r.data,
    'min_build', r.min_build, 'is_active', r.is_active
  ) order by r.row_id), '[]'::jsonb),
  'seed_from_csv.py',
  'seed from repo CSVs (Assets/Resources/Data/ticket_types.csv)'
from content_rows r
where r.catalog = 'ticket_types'
on conflict (catalog, version) do nothing;

-- ------------------------------------------------------------------------
-- Publish the seed: every catalog goes to v1.
-- ------------------------------------------------------------------------
update content_catalogs
   set published_version = 1, updated_at = now()
 where name in ('gacha_banners', 'gacha_rates', 'gacha_pools', 'ticket_types')
   and published_version < 1;

commit;

-- ------------------------------------------------------------------------
-- VERIFICATION — run after applying, paste the output.
-- Expected: gacha_banners 4, gacha_rates 6, gacha_pools 11, ticket_types 2
-- ------------------------------------------------------------------------
select catalog, count(*) as rows, min(version) as min_v, max(version) as max_v
  from content_rows group by catalog
union all
select 'DRAFTS:' || catalog, count(*), null, null
  from content_drafts group by catalog
 order by 1;

select name, published_version, is_enabled from content_catalogs order by name;
