using System.Collections.Generic;
using NUnit.Framework;

namespace Golfin.Content.Tests
{
    /// <summary>
    /// The bundled cursor parser. Everything here is about ONE guarantee: a bad
    /// <c>content_version.txt</c> costs a full payload, never a boot. There is no input that may
    /// throw, and every failure resolves to 0 (= "I hold none of that catalog" = send everything).
    /// </summary>
    public class ContentVersionFileTests
    {
        [TearDown]
        public void TearDown() => ContentVersionFile.ResetForTest();

        [Test]
        public void Parse_ReadsTheRealExporterFormat()
        {
            var map = ContentVersionFile.Parse(
                "bags=1\nballs=5\ncharacters=5\nclubs=1\nitems=1\nshop_catalog=3\ntexts=11\n");

            Assert.AreEqual(11, map["texts"], "texts= is the line Phase 1 actually sends.");
            Assert.AreEqual(3, map["shop_catalog"], "An underscore in the catalog name must survive.");
            Assert.AreEqual(7, map.Count);
        }

        [Test]
        public void Parse_ToleratesCrlf_BlankLines_And_Comments()
        {
            var map = ContentVersionFile.Parse("# generated by export_content.py\r\n\r\ntexts=11\r\n");
            Assert.AreEqual(11, map["texts"]);
            Assert.AreEqual(1, map.Count, "The comment and the blank line must not become catalogs.");
        }

        [Test]
        public void Parse_GarbageLine_IsSkipped_NotThrown_AndCostsOnlyThatCatalog()
        {
            // The skipped lines log warnings, not errors, so nothing here trips the test runner.
            var map = ContentVersionFile.Parse("texts=11\nthis is not a pair\nclubs=notanumber\n=5\n");

            Assert.AreEqual(11, map["texts"], "A good line before the garbage still applies.");
            Assert.IsFalse(map.ContainsKey("clubs"),
                "An unparseable version must leave the catalog with NO cursor, which is 0, " +
                "which is a full payload — never some other catalog's cursor.");
            Assert.AreEqual(1, map.Count);
        }

        [Test]
        public void Parse_NegativeVersion_ClampsToZero_MatchingTheServer()
        {
            var map = ContentVersionFile.Parse("texts=-4\n");
            Assert.AreEqual(0, map["texts"],
                "The server's own parse_since clamps to 0; the client must not send a value the " +
                "server will reinterpret.");
        }

        [Test]
        public void Parse_DuplicateName_KeepsTheLast()
        {
            var map = ContentVersionFile.Parse("texts=3\ntexts=11\n");
            Assert.AreEqual(11, map["texts"]);
        }

        [Test]
        public void Parse_NullOrEmpty_IsAnEmptyMap_NotAnException()
        {
            Assert.AreEqual(0, ContentVersionFile.Parse(null).Count);
            Assert.AreEqual(0, ContentVersionFile.Parse("").Count);
            Assert.AreEqual(0, ContentVersionFile.Parse("   \n\n  ").Count);
        }

        [Test]
        public void VersionFor_UnknownCatalog_IsZero_SoTheServerSendsEverything()
        {
            ContentVersionFile.ConfigureForTest(new Dictionary<string, int> { { "texts", 11 } });
            Assert.AreEqual(0, ContentVersionFile.VersionFor("clubs"));
            Assert.AreEqual(0, ContentVersionFile.VersionFor(null));
            Assert.AreEqual(0, ContentVersionFile.VersionFor("  "));
        }

        [Test]
        public void VersionFor_ReadsTheRealBundledFile()
        {
            ContentVersionFile.ResetForTest();

            int texts = ContentVersionFile.VersionFor(RemoteContentSource.TextsCatalog);

            Assert.Greater(texts, 0,
                "Assets/Resources/Data/content_version.txt must ship a texts= line. If this fails, " +
                "every client asks for the FULL texts catalog on every boot — recoverable, but it " +
                "means the exporter (CONTENT_PIPELINE_PLAN I3) did not run before the build.");
        }
    }
}
